### ISSUE TITLE
Testing LSF Support

### ISSUE THREAD

**Issue by bpanneton** [chu11/magpie#81]
I'm attempting to add LSF support to the testsuite and running into a bunch of issues. I'm hoping we can maybe make it more modular and possibly simpler in order to add new tests.

I figured I'd make an issue to document everything and get your feedback.

The first problem I have noticed is that I would need to run no-local on all of my tests. I have set it up to have standardtests and nolocaldirtests be able to run separately.  Thus I can just turn off standard tests and keep nolocaldirtests on. This seems to work.

The next issue I have noticed is if I run the Default tests, all the BasicJobSubmits kick off at the same time. This causes Hadoop to use the same ports and crash in some cases. I'm not sure how to correct this yet other than making dependencies. Thoughts?

I'll add more as I come to them.

**Comment by chu11** [comment]
The testing scripts are by no means pretty, my attempt just to get something going.

Regarding the no-local, you're right.  I originally scripted them under the assumption that you'd always want to run the non-no-local.   So we should probably have another flag or something to allow running one or the other or both.

Splitting up the testing scripts into individual files is a great idea.  They are getting very long.

I'm a little confused by what you mean "Hadoop to use the same ports and crash in some cases"??  The jobs should be running independently of each other, because the HADOOP_PER_JOB_HDFS_PATH option is set to yes.

I can do some of these things.  Perhaps having an option to allow standard tests & no-local-dir tests is the first thing to do?

**Comment by bpanneton** [comment]
Hmm, I saw an issue with the port was in use, but perhaps it was from a different reason. I 'should' be running on separate nodes so that shouldn't be an issue anyhow.

**Comment by bpanneton** [comment]
Also for the default tests, can we turn some on and off? For instance I am not running with pig, storm or mahout. Those tests will always fail.

**Comment by bpanneton** [comment]
So I think I got the general default tests working with lsf. Before you start making changes to it, perhaps I should send you what I have and make sure it works on your systems.

**Comment by chu11** [comment]
Why don't you send me your first pull request, then we can go from there.    The issues I see (and we can create new tickets for this) are:

allow running standard, no-local-dir, or both tests
allow default tests to not run pig, storm, etc. whatever user doesn't need.
make more modular

**Comment by bpanneton** [comment]
Okay ill send something over eventually

**Comment by bpanneton** [comment]
Is there a reason you broke up hadoop versions 2.2.0-2.6.1 and 2.7.0-2.7.1?

**Comment by chu11** [comment]
"broke up"?  Not sure what you're referring to.

**Comment by bpanneton** [comment]
Sorry I mean on the test-submit.sh under hadooptests you have strings like:
...
        for hadoopversion in 2.2.0 2.3.0 2.4.0 2.4.1 2.5.0 2.5.1 2.5.2 2.6.0 2.6.1
...
        for hadoopversion in 2.7.0 2.7.1
....

**Comment by chu11** [comment]
Ahhh.  The "broke up" is due to some type of dependency.  In the case of the hadoop breakup you list above, it's because the Apache builds depend on different Java versions.  Elsewhere, you may find "broke up" because of dependencies on other projects.  The pig versions are broken up based on the Hadoop version they will be tested against.

**Comment by bpanneton** [comment]
I think this is solved.
